name: dart_websocket_client_test
description: A client-side dart_websockets test
version: 1.0.0
homepage: https://github.com/Derrick56007/dart_websockets

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  dart_websockets: any

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
