name: dart_websockets
description: A starting point for Dart libraries or applications.
version: 1.0.5
homepage: https://github.com/Derrick56007/dart_websockets

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http_server: ^0.9.8+3
  pedantic: ^1.9.0

dev_dependencies:
  test: ^1.14.4
